// PHNTM — samurai / Musashi-spirit lines shown when an account's max loss is breached.
// Original paraphrases in the register of the Book of Five Rings & the Dokkōdō — not verbatim translations.
window.PHNTM_FAIL_QUOTES = [
  "Even Musashi lost duels before he won sixty. The blade that broke today is reforged tomorrow.",
  "The account is gone. The lesson is not. Keep the lesson.",
  "A wall was struck. Walls teach the hand where not to swing.",
  "You did not fail — you found the edge of the cliff without falling off it forever.",
  "The samurai who never lost never truly fought. You fought.",
  "Defeat is a teacher who charges tuition. Pay it, and learn.",
  "The drawdown closed the gate. Discipline holds the key to the next one.",
  "Musashi wrote: do nothing that is of no use. This loss was of use — study it.",
  "A sword bent is not a sword broken. Straighten it. Return.",
  "The mountain was not moved today. Tomorrow you carry a smaller stone.",
  "Every master was once a disaster who refused to quit.",
  "The river breached its bank. Rebuild the bank an inch higher.",
  "You met the limit. Now you know exactly where it lives.",
  "Fall seven times, rise eight. This is the fifth fall. Three remain.",
  "The strongest steel is folded a thousand times, and burned each time.",
  "A single defeat is a rumor, not a verdict. Answer it.",
  "The way is in training. Training includes the days you break.",
  "The blade does not mourn the miss. It resets its stance.",
  "This is not the end of the war. It is the end of a bad position.",
  "Lucid took the account. It cannot take the reps you earned taking it.",
  "The warrior accepts loss the way the field accepts rain — and grows.",
  "You breached the line because you were close enough to touch it. Come back closer.",
  "Perceive that which cannot be seen with the eye: your own tilt. Now you have seen it.",
  "The empty account is a clean slate. Musashi began every duel with nothing but stance.",
  "A loss respected becomes armor. A loss ignored becomes a habit.",
  "The tide went out. It does not ask permission to return.",
  "You did not lose money. You paid for a map of the drawdown.",
  "The bamboo that bends survives the storm the oak does not.",
  "Cut once, cleanly, next time. Today you learned the cost of cutting twice.",
  "Musashi slept on stone so victory would feel like silk. Sleep on this.",
  "The account died so the trader could live. Honor the trade.",
  "There is no fear in a stance already fallen. Only the next stance.",
  "You have been humbled. The humbled hand grips the blade correctly.",
  "The stone is split not by the last strike, but by all before it. Keep striking.",
  "A closed account is a closed chapter, not a closed book.",
  "The wave that drowns you today teaches you to swim tomorrow.",
  "Do not regret what you have done. Refine what you will do.",
  "The limit is a wall only until you learn to walk beside it.",
  "Even the sharpest blade is dull the morning it is forged. Sharpen.",
  "You reached the floor. Now you know how far the floor is.",
  "The samurai does not curse the ground he fell on. He studies its slope.",
  "One breach is data. Two is a pattern. Do not let it become two.",
  "The candle that guttered still showed you the room.",
  "Musashi feared no opponent but his own impatience. Meet yours.",
  "A drained account is the price of a lesson the charts refused to teach for free.",
  "The gate closed. Gates open for those who wait with a plan.",
  "You are not broken. You are between forms.",
  "Loss is the whetstone. Press the blade to it and do not flinch.",
  "The mountain remembers every climber who turned back and returned stronger.",
  "This defeat has no power over tomorrow unless you carry it there.",
  "The old account is ash. From ash, the disciplined build the forge.",
  "Strike the root of the error, not the leaf of the loss.",
  "You have seen your limit. Most traders die never having met theirs.",
  "The sea does not apologize to the shore. Neither should you to the market. Adjust.",
  "A warrior counts losses as lessons and lessons as capital.",
  "Fall with your eyes open and you will know why you fell.",
  "The reed survives the flood the tree cannot. Bend, then stand.",
  "Musashi carved his sword from a wooden oar and still won. Tools do not make the trader.",
  "Today the market was the teacher. Tomorrow, be the student who returns.",
  "The account balance is zero. Your resolve is not.",
  "There is timing in everything. Yours was off. Timing can be trained.",
  "The blade shattered on the stone it was meant to cut. Reforge it thinner and truer.",
  "You did not drown. You touched the bottom and learned where it is.",
  "A samurai's first loss is his most honest mirror. Look.",
  "The path narrows here so it may widen ahead.",
  "Grief for the account is a luxury. The disciplined trade tomorrow instead.",
  "The storm passed through the gate you left open. Close it and rebuild.",
  "Every scar is a sentence in the book only you can read.",
  "Musashi: think lightly of yourself and deeply of the world. Think deeply of this drawdown.",
  "The wall you struck marks the border of who you were, not who you become.",
  "A defeat survived is a rehearsal for a victory earned.",
  "The empty scabbard waits patiently for a sharper blade.",
  "You lost the position, not the discipline. The discipline compounds.",
  "The mountain did not reject you. It measured you. Measure again.",
  "Fire that burns the field clears it for a stronger harvest.",
  "One breach does not unmake a thousand good decisions. Make the thousand-and-first.",
  "The samurai bows to the opponent who defeats him, then trains to reverse the bow.",
  "This is a closed door in a long corridor. Keep walking.",
  "The drawdown is a debt to your future self. Repay it with patience.",
  "A blade tested to breaking teaches the smith where to fold.",
  "You have failed the account, not the mission. The mission continues.",
  "The current pulled you under because you swam without a stance. Find your stance.",
  "Do not seek to follow the winners. Seek what the winners sought — and lost for.",
  "The night the account died is the night the trader was born.",
  "Every great climb has a fall recorded in its earliest pages.",
  "The limit held because it was built to. Build yours the same way.",
  "Musashi mastered the void by first being emptied. You are emptied. Now master it.",
  "A single storm does not end the season. Plant again.",
  "You met the floor with your eyes open. That is not defeat. That is reconnaissance.",
  "The sharpest lesson leaves the deepest cut. Let it heal into resolve.",
  "The account is a boat. Boats are rebuilt. Sailors are not so easily replaced — and you remain.",
  "Turn the loss over in your hand until you can name every edge of it.",
  "The warrior who fears the drawdown has already lost to it. You faced it.",
  "This wall is not your tomb. It is your starting line.",
  "The blade returns to the whetstone, not the trash. So do you.",
  "You have spent the tuition. Now attend the lesson it bought.",
  "Musashi: perceive things that cannot be seen. You just saw your ceiling. Raise it.",
  "The account fell so you would finally respect the line. Respect it, and return.",
  "One loss, honestly examined, is worth more than ten wins never questioned.",
  "The forge is hottest before the finest blade. Step back into the fire."
];

// Shown when a prop account clears its profit target — victory in the samurai register.
window.PHNTM_PASS_QUOTES = [
  "The target falls. Musashi bowed to no one on the day he earned his name.",
  "The blade was tempered in ten thousand cuts. Today it found its mark.",
  "You did not chase the win. You waited, and it came to you.",
  "The mountain is climbed. Now learn to breathe at the summit.",
  "Discipline was the sword. Patience was the hand. The target is yours.",
  "A thousand quiet mornings built this single loud victory.",
  "The warrior who masters himself masters the market. You have crossed.",
  "The way was in training. The proof is on the ledger.",
  "You met the goal the way water meets the sea — inevitably, without haste.",
  "Victory belongs to the trader who was already prepared to lose and refused to.",
  "The target is cleared. Do not celebrate the strike — celebrate the stance that earned it.",
  "Musashi won sixty duels by never fighting the wrong one. You chose well.",
  "The gate opens. Walk through it the same disciplined way you approached it.",
  "This is not luck. Luck is not repeatable, and you will do this again.",
  "The blade is proven. Sheathe it with the same calm you drew it.",
  "You have earned the next arena. Enter it humble and armed.",
  "The summit rewards the climber who never looked down at the drawdown.",
  "Steel remembers every fold. Your account remembers every disciplined day.",
  "The target bows to the trader who never bowed to fear.",
  "One victory, honestly earned, is worth more than a hundred gambled."
];

// Shown when the profit target is reached but the consistency rule is not yet met —
// not a failure, a "not yet." Musashi discipline + Alexander's measured conquest.
window.PHNTM_CONSIST_QUOTES = [
  "The target is met, but one day carries too much of the victory. Alexander did not win Persia in a single charge — he won it evenly, province by province.",
  "You reached the summit in one leap. The rule asks you to build the stairs. Keep climbing.",
  "Musashi: the true cut is many small cuts, not one wild swing. Balance the ledger and the pass is yours.",
  "Alexander never let one battle define the campaign. Do not let one day define your account.",
  "The goal is touched, not yet earned. Spread the profit as a general spreads his forces — no single line overextended.",
  "A river that floods in one day floods the plain. A river that flows steadily feeds the kingdom.",
  "You have the profit. Now prove it was skill, not a storm. Trade on, evenly.",
  "Alexander conquered by never outrunning his supply lines. Your best day outran the rest — let them catch up.",
  "The blade is sharp enough. Now show it can cut the same way twice.",
  "One towering day is a rumor of skill. A row of even days is the verdict. Earn the verdict.",
  "The mountain is reached, but the path behind you is uneven. Walk it again, smoother.",
  "Musashi distrusted the single brilliant strike. Consistency is the discipline that survives him. Return to it.",
  "You struck true once. The rule asks: can you do it without the lightning? Show it.",
  "Great empires fall to one reckless day. Great accounts pass on many quiet ones. Choose quiet.",
  "The target bows, but the rule stands guard. Balance your days and it steps aside.",
  "Alexander rested his army to conquer longer. Rest the one loud day; let the calm ones speak.",
  "Profit gathered in a single storm is not yet yours to keep. Gather it again, gently.",
  "The summit is here. The rule only asks that you did not fly — that you walked. Walk it once more.",
  "A wall is breached evenly or not at all. Your best day leaned too hard. Steady the ladder.",
  "You have proven you can win. Now prove you can win the same size twice. That is the whole game.",
  "The general who wins one glorious battle and loses the war is forgotten. Win evenly. Be remembered.",
  "Consistency is not a cage — it is the proof that today was not an accident.",
  "One day did the work of five. The rule wants five days that each did their share. Give them their share.",
  "Musashi trained the ordinary cut until it was extraordinary. Make your ordinary day the one that passes you.",
  "You are one balanced week from the gate. Do not force it — flow into it.",
  "The target is a door you have already reached. Consistency is the key still in your other hand. Turn it."
];
